name: helloworld-1.0.$(Rev:.r)

trigger:
- master

pool:
  name: default

variables:
  - name: buildConfiguration
    value: 'Release'

  - name: packageName
    value: 'helloworld'

  - group: mysecrets

steps:
- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build project'

- script: |
    dotnet pack --configuration $(buildConfiguration) \
                /p:PackageId=$(packageName) \
                /p:PackageVersion=1.0.$(Build.BuildId) \
                --no-build \
                --output 'helloworld-artifacts'
  displayName: 'Pack NuGet package: helloworld-1.0.$(Build.BuildId)'

- script: dotnet nuget push "helloworld-artifacts/*.nupkg" \
          --source "hello-world" \
          --api-key $(azureArtifactsPAT)
  displayName: 'Push NuGet package to Azure Artifacts'

