name: 1.0.$(Rev:.r)

trigger:
- master

pool:
  name: default

variables:
  buildConfiguration: 'Release'
  packageName: 'helloworld'

# ✅ Add this block:
steps:

# ensure dependencies
- script: dotnet restore
  displayName: 'Restore dependencies'

# build the project
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build project'

# Pack with dynamic version number based on the build number
- script: |
    dotnet pack --configuration $(buildConfiguration) \
                /p:PackageId=$(packageName) \
                /p:PackageVersion=1.0.$(Build.BuildId) \
                --no-build \
                --output 'helloworld-artifacts'
  displayName: 'Pack NuGet package: helloworld-1.0.$(Build.BuildId)'


