name: 1.0.$(Rev:.r)

trigger:
- master

# ✅ Use self-hosted agent pool
pool:
  name: self-hosted-pool  # Replace with your actual pool name if different

variables:
  buildConfiguration: 'Release'
  packageName: 'helloworld'

# ✅ Add this block:
steps:

# ensure dependencies
- script: dotnet restore
  displayName: 'Restore dependencies'

# build the project
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build project'

# Pack with dynamic version number based on the build number
- script: |
    dotnet pack --configuration $(buildConfiguration) \
                /p:PackageId=$(packageName) \
                /p:PackageVersion=$(packageName)-$(Build.BuildId) \
                --no-build \
                --output 'helloworld-artifacts'
  displayName: 'Pack NuGet package: helloworld-$(Build.BuildId)'

